### ISSUE TITLE
no .env file found for implement the app

### ISSUE THREAD

**Issue by DaiyongBug** [joaovitoriasilva/endurain#12]

**Comment by joaovitoriasilva** [comment]
Hello thanks for reaching out. Can you provide more details on how are you deploying the container?

**Comment by DaiyongBug** [comment]
> Hello thanks for reaching out. Can you provide more details on how are you deploying the container?

I just use the docker-compose up. am i wrong with this? can you please provide a list for deploying by docker.

**Comment by joaovitoriasilva** [comment]
Hi @pflavio thanks for the help. I will look into this to better address the issue

**Comment by joaovitoriasilva** [comment]
Hello. 

This will be fixed in the upcoming v0.2.0 release.

**Comment by joaovitoriasilva** [comment]
Fixed on version v0.2.0
