### ISSUE TITLE
Feature Request: Docker image

### ISSUE THREAD

**Issue by SchaffRita** [joaovitoriasilva/endurain#15]
It's not urgent but would it be possible to create and maintain a Docker image?
I saw that you are also providing the Dockerfiles, however, it would be even easier (and perhaps more enticing for people) if they saw that they could quickly run this with a command.
Thanks for considering this request.

**Comment by joaovitoriasilva** [comment]
Thanks for reaching out. I already provide docker images. One for the backend and another for the frontend.

Are you referring to a single docker image that contains everything?

**Comment by joaovitoriasilva** [comment]
Closing this issue because there was no response
