### ISSUE TITLE
Endurain on raspberry pi

### ISSUE THREAD

**Issue by gwenvador** [joaovitoriasilva/endurain#16]
Is there a docker version compatible with arm processor? Currently endurain does not run on a raspberry pi.

**Comment by joaovitoriasilva** [comment]
Hello, thanks for reaching out. I will check this today. Nevertheless can you share some logs of the error you are getting?

Thank you

**Comment by gwenvador** [comment]
Hi. I have issue on the backend and frontend containers. 
- for backend: `exec /usr/local/bin/uvicorn: exec format error`
- for frontend: `exec /usr/local/bin/docker-php-entrypoint: exec format error`

**Comment by joaovitoriasilva** [comment]
Hello again. The current image only supports amd64 architecture. In the next release (maybe next week??) it will support multi arch (amd64 and arm64).

In the meantime you can build locally by changing the backend and frontend docker image files.
- Backend:
```
# Change line 1 from FROM python:3.11 to:
FROM arm32v7/python:3.11 # if arm 32 bits
FROM arm64v8/python:3.11 # if arm 64 bits
```
- Frontend:
```
# Change line 2 from FROM node:20-alpine as build-stage to:
FROM arm32v7/node:20-alpine as build-stage # if arm 32 bits
FROM arm64v8/node:20-alpine as build-stage # if arm 64 bits
# Change line 21 from FROM nginx:alpine as production-stage to:
FROM arm32v7/nginx:alpine as production-stage # if arm 32 bits
FROM arm64v8/nginx:alpine as production-stage # if arm 64 bits
``` 

I can't test this because I don't have an arm device like a Raspberry Pi to test it. I appreciate your feedback on this and if you need further assistance, please reach out.

**Comment by joaovitoriasilva** [comment]
Hello again, can you try with tag "dev_24072024" instead of "latest"?

Thank you.

**Comment by gwenvador** [comment]
Hi. The docker image are correctly pulled for the raspberry pi. Thanks for that.

**Comment by joaovitoriasilva** [comment]
You're welcome. Later today or tomorrow I will release version 0.3.0 that has this change and fixes a couple of bugs present in this dev release.

**Comment by joaovitoriasilva** [comment]
Hi @bossenti, thanks for reaching out and thanks for the suggestion!

I don't want to sound like a jerk but after thinking it over, I’ve decided not to add support for 32-bit (linux/arm/v7) images. This architecture is a bit outdated, and pretty much everything is moving towards 64-bit. Most modern hardware supports 64-bit, and keeping things simpler and future-proof just makes sense. For example Home Assistant is dropping support for 32-bit.

**Comment by joaovitoriasilva** [comment]
Thanks for understanding. Maybe this can help https://docs.endurain.com/developer-guide/
