### ISSUE TITLE
Unable to create new user or change admin password

### ISSUE THREAD

**Issue by jrhbcn** [joaovitoriasilva/endurain#19]
Thanks for this nice piece of software. I am unable to set any passwords (neither for new users nor for the admin one) as all password captions give the "Password does not meet requirements". I have made sure the password does meet requierements as I am using capitals, numbers, and special characters. However, the message persists and can do anything else.

Using latest version 0.3.0

Regards,

**Comment by jrhbcn** [comment]
OK, I have managed to create a password. Basically, the characters "." or "=" are not treated as spacial ones, however "$" is.

**Comment by joaovitoriasilva** [comment]
Hi. Thanks for reaching out. I will add these characters as well to the regex expression. It makes sense. 

I will probably add all specified in here https://owasp.org/www-community/password-special-characters

**Comment by joaovitoriasilva** [comment]
Fixed on version v0.3.1
