### ISSUE TITLE
Feature request: pannable/zoomable map

### ISSUE THREAD

**Issue by rhyst** [joaovitoriasilva/endurain#31]
The leaflet map shown is a static overview of the full track of the activity. It would be good if the controls were enabled to allow panning/zooming round the map. At the moment you can double click to zoom in, but then can't zoom out or pan.

**Comment by joaovitoriasilva** [comment]
Hi, thanks for reaching out. Will do that for next release.

**Comment by joaovitoriasilva** [comment]
@rhyst I am sorry, I forgot to release this on v0.6.0. I will implement this on v0.6.1.

**Comment by joaovitoriasilva** [comment]
Implemented in v0.6.1
