### ISSUE TITLE
Docker-Compose.yml lists incorrect paths

### ISSUE THREAD

**Issue by TheBig-O** [joaovitoriasilva/endurain#37]
When setting up my docker container, I used the example compose file. After getting it set up, I tried importing some saved runs with no success. Hitting the "Import" button had no effect.
 After reading through the ReadMe file and comparing it to the compose file, I realized what the issue was. The paths were not the same. In the compose file, the paths are listed as:
 ```
    volumes:
    #  - <local_path>/endurain/backend/app:/app # Configure volume if you want to edit the code locally by cloning the repo
      - <local_path>/endurain/backend/user_images:/app/user_images # necessary for user image persistence on container image updates
      - <local_path>/endurain/backend/bulk_import:/app/bulk_import # necessary to enable bulk import of activities. Place here your activities files

```

The readme file says:
```
<local_path>/endurain/backend/files/bulk_import:/app/files/bulk_import
<local_path>/endurain/backend/files/processed:/app/files/processed
```

The compose file is missing the intermediate `files` directory. (It's also missing any mention of the `processed` folder.)
Once I corrected these issues and added the directory, importing worked just fine.
Just wanted to point it out so it will avoid future questions about why bulk import doesn't work.

**Comment by joaovitoriasilva** [comment]
Thanks for reaching out and for finding the error. I forgot to change the example file.

Once I am on the computer I will fix this.

**Comment by joaovitoriasilva** [comment]
File updated. Thanks for the heads up and I am sorry for missing this.
