### ISSUE TITLE
SQL-Issue

### ISSUE THREAD

**Issue by gstoetti94** [joaovitoriasilva/endurain#38]
HortusFox is run on Docker. I upgraded to v 3.7.
When trying to edit items in Administration-Environment, I get the error message:

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'custom_media_share_host' in 'field list' `

It occured when I tried to add the Pl@ntNet-API.

HortusFox v3.7
PHP Version: 8.3.0
MySQL Version: 10.11.9-MariaDB-ubu2004

**Comment by gstoetti94** [comment]
Sorry - wrong Firefox-Tab :-/

**Comment by joaovitoriasilva** [comment]
No problem 😀
