### ISSUE TITLE
Cannot connect with Strava

### ISSUE THREAD

**Issue by rubenixnagios** [joaovitoriasilva/endurain#43]
Hello first of all thanks for such a nice work, I appreciated it so much. I like strava but I also like store my sensitive data on my datacenter...
I just I cannot get strava integration to work. Followed instructions, started over and over again and got this error:

{"message":"Bad Request","errors":[{"resource":"Application","field":"redirect_uri","code":"invalid"}]}

Also dont know how to publish this app behind Nginx Proxy and publish it on the net (maybe thats the problem with strava integration...)
what need to type in the following fields (website / Authorization callback domain) ¿? Im quite lost as u can see....
![imatge](https://github.com/user-attachments/assets/e698513c-f948-4c8a-89c4-6b9c9835eb9b)
Any help would be really appreciated.
congratulations for such a nice work!

**Comment by rubenixnagios** [comment]
@joaovitoriasilva got it working; strava integration works!! is it a good idea to have both integrations? strava & garmin ¿?
I see that got duplicates on activities. I think it would be great to join activities with same distance on same date for example.
just an idea:
![imatge](https://github.com/user-attachments/assets/a8e86ac6-c912-4238-addd-ed403b8a359f)
what do u think? can be done?

also, any chance to add catalan onto crowdin translations? il be glad to translate it (maybe to many subjects on same issue :smirk:

**Comment by rubenixnagios** [comment]
nevermind about the crowdin translation...i created a topc there.

**Comment by joaovitoriasilva** [comment]
Sorry @rubenixnagios for not answering earlier but I was compiling a comprehensive response to try to help you.

However you have seem to handle it, and that's great. Glad to hear that it is working.

Regarding the activity merge, I don't think that is a good idea. Strava API terms state that if you unlink Strava, every Strava data must be deleted, so unlinking Strava would delete Strava and GC activities if they were merged.

For the localization I will check it when I am on the computer. Thank you for your desire to contribute for the project.

**Comment by rubenixnagios** [comment]
fair enought then, didn't read Strava API terms....however do not understant it...I did not meant to unlink strava...maybe to put an icon next to the activity to just to let the user know that the activity was found on both clouds...dunno...

**Comment by joaovitoriasilva** [comment]
I will close this issue. I will not apply this in the meantime.
