### ISSUE TITLE
retrieve garmin activities from API...possible?

### ISSUE THREAD

**Issue by rubenixnagios** [joaovitoriasilva/endurain#44]
Any chance to make a curl request within the API to retrieve activities from garmin connect?
if so, how can I achieve this?

Thanks so much again!

**Comment by rubenixnagios** [comment]
Are the garmin activities retrieved automatically once gets uploaded to garmin cloud or just when the button is pressed?
if activities are not in sync maybe its possible to make a curl request every x hours via cronjob or similar...and then it pulls the latest activities...makes sense? sorry but english is not my main language...

**Comment by joaovitoriasilva** [comment]
I just noticed that this is not documented, so I will add this to the documentation later today probably.
Once the integration with Garmin Connect is configured, every hour the backend will check if there is new unimported activities. If yes, the new activity is automatically imported.

This is also the behavior for Strava.

**Comment by joaovitoriasilva** [comment]
Changes in docs implemented in v0.6.1
