### ISSUE TITLE
Can't assign gear to activity

### ISSUE THREAD

**Issue by spiezmaestro** [joaovitoriasilva/endurain#55]
I have gear created,

![image](https://github.com/user-attachments/assets/efac306e-ead1-42e9-b0b4-05140a225d5e)

but they are not listed, when I want to add gear to an activity. The dropdown menu stays empty.

![image](https://github.com/user-attachments/assets/7f2f3ff5-aed9-4af7-a8c2-427965aea3c9)

I have checked logging, but there are no messages at the timestamp I'm trying to add the gear.

**Comment by joaovitoriasilva** [comment]
Hi. Thanks for reaching out. You are trying to add the gear to what type of activity?

Running, walk, other?

**Comment by spiezmaestro** [comment]
I have tried adding shoes to hiking/walking. Your answer hinted that the gear is dependent on activity type. I just tried to add gear to a ride and there the two bikes were in the drop-down list. So shoes are apparently not selected when trying to add to hiking and walking.

**Comment by joaovitoriasilva** [comment]
Yep, probably the filter is not considering hike/walk activities. I will check this for the next release.

**Comment by joaovitoriasilva** [comment]
Hello. This should be fixed in v0.6.5. I will close the issue, but if the issue persists please feel free to open it again.

Thank you.
