### ISSUE TITLE
reduce number of docker containers

### ISSUE THREAD

**Issue by leonardpitzu** [joaovitoriasilva/endurain#60]
It would be great to have just one container for front- and backend and an optional one for the DB (maybe also be able to switch to postgres) if the user wishes to do so.

**Comment by joaovitoriasilva** [comment]
Hello, thanks for reaching out. Working on it :)

**Comment by joaovitoriasilva** [comment]
Hello, postgres will be added in next release. Simplified docker setup in the following probably

**Comment by leonardpitzu** [comment]
Much appreciated!

**Comment by joaovitoriasilva** [comment]
Number of containers reduced to 1 in v0.7.0
