### ISSUE TITLE
GPLv3 to AGPLv3

### ISSUE THREAD

**Issue by joaovitoriasilva** [joaovitoriasilva/endurain#61]
Propose to change license from GPLv3 to AGPLv3.
- @movassaghi6 
- @eltociear 
- @LeonardSchwier 
- @ThreeCO 

As contributors of this project I would like your input. AGPLv3 is better suited for Endurain while maintaining all the key aspects of the current license.

**Comment by joaovitoriasilva** [comment]
Hello again,

I wanted to follow up on this proposal. If no objections are raised by December 31 2024, I will proceed under the assumption that everyone is in agreement with the change. Please feel free to share your thoughts before then.

Thank you!

**Comment by ThreeCO** [comment]
That definitely makes sense!

**Comment by joaovitoriasilva** [comment]
License changed
